spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:duckdb:./data/finbench_sf0_1.duckdb}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.duckdb.DuckDBDriver}
spring.datasource.hikari.maximum-pool-size=${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:2}
spring.datasource.hikari.minimum-idle=${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:1}
spring.datasource.hikari.data-source-properties.allow_unsigned_extensions=${SPRING_DATASOURCE_ALLOW_UNSIGNED_EXTENSIONS:true}
spring.flyway.enabled=${SPRING_FLYWAY_ENABLED:false}
